# -*- coding: utf-8 -*-
"""kadai_008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ke8701n1xuifajfgk3ftsNJKU1ZdEHzk
"""

#ランダムな整数を利用するため、randomモジュールをインポート
import random

#変数varに0～100までのランダムな整数を算入する
var = random.randint(0,100)

#変数varが3の倍数の場合は「Fizz」を出力
if var % 3 ==0 and var % 5 ==0:
  print("FizzBuzz")
elif  var % 3 ==0:
  print("Fizz")
elif var % 5 ==0:
  print("Buzz")
else:
  print(var)