# -*- coding: utf-8 -*-
"""kadai_007

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1osZ-xwdKlzIbDWMS0B-4P0yDKfP_vNZb
"""

#dictionaryに入れる文字
dictionary = {"mon": "晴れ", "tue": "雨", "wed":"晴れ","thu": "晴れ","fri": "曇り", "sat": "曇りのち雨", "sun":"雷雨"}

# dictionary表示
print(dictionary)

#arrayに入れる文字
array = ["月曜日は晴れです","火曜日は雨です","水曜日は晴れです","木曜日は晴れです","金曜日は曇りです","土曜日は曇りのち雨です","日曜日は雷雨です"]

# array表示
print(array)